# Generated by Django 3.0.6 on 2020-06-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0006_auto_20200608_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(default='default.jpg', upload_to='gallery')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('article', models.ManyToManyField(to='blog.Article')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
