# Generated by Django 3.0.6 on 2020-06-08 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20200608_1516'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
