# Generated by Django 3.0.6 on 2020-06-08 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200608_1455'),
        ('gallery', '0004_gallery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Article'),
        ),
    ]
