# Generated by Django 3.0.6 on 2020-06-08 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20200608_1606'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['-created_on'], 'verbose_name_plural': 'galleries'},
        ),
    ]
