# Generated by Django 3.0.6 on 2020-06-08 13:38

from django.db import migrations, models
import gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_auto_20200608_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=gallery.models.set_image_save_path),
        ),
    ]
