# Generated by Django 3.0.6 on 2020-06-10 13:50

from django.db import migrations
import django_resized.forms
import gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_auto_20200608_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_thumbnail',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=75, size=[230, 130], upload_to=gallery.models.set_image_save_path),
        ),
    ]
