# Generated by Django 3.0.6 on 2020-06-11 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0010_image_image_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_thumbnail',
        ),
    ]
