# Generated by Django 3.0.6 on 2020-06-12 10:35

from django.db import migrations
import gallery.models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0011_remove_image_image_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='size_large',
            field=imagekit.models.fields.ProcessedImageField(default='default.jpg', upload_to=gallery.models.set_image_save_path),
        ),
    ]
