# Generated by Django 3.0.6 on 2020-05-29 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Article title')),
                ('pub_date', models.DateTimeField(verbose_name='Date published')),
                ('image_url', models.CharField(max_length=2083, verbose_name='Image url')),
                ('content', models.TextField(verbose_name='Article content')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.ArticleCategory')),
            ],
        ),
    ]
