# Generated by Django 3.0.6 on 2020-05-29 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticleCategory',
            new_name='ArticleCategories',
        ),
    ]
