# Generated by Django 3.0.6 on 2020-06-03 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_articlecomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlecomment',
            name='pub_date',
        ),
    ]
