# Generated by Django 3.0.6 on 2020-06-08 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200608_1455'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecategories',
            options={'verbose_name_plural': 'article categories'},
        ),
    ]
