# Generated by Django 3.0.6 on 2020-06-09 14:49

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200608_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cover_photo',
            field=models.ImageField(default='default.jpg', upload_to=blog.models.set_image_save_path),
        ),
    ]
