# Generated by Django 3.0.6 on 2020-06-10 13:50

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_article_cover_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AlterField(
            model_name='article',
            name='cover_photo',
            field=models.ImageField(blank=True, default='default.jpg', upload_to=blog.models.set_image_save_path),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_url',
            field=models.CharField(blank=True, max_length=2083, verbose_name='Image url'),
        ),
    ]
