# Generated by Django 3.0.6 on 2020-06-12 11:22

import blog.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200610_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='cover_photo',
        ),
        migrations.RemoveField(
            model_name='article',
            name='image_url',
        ),
        migrations.AddField(
            model_name='article',
            name='carousel_img',
            field=imagekit.models.fields.ProcessedImageField(default='default.jpg', upload_to=blog.models.set_image_save_path),
        ),
    ]
